Link login front to back
HE-Arc/FirstPass pull request #3
Opened 2023-02-27 16:51 UTC by TimothyPeck

2023-02-27 23:33 UTC, Xstoudi commented
Pour la partie CORS : pas besoin de mettre `localhost` ET `127.0.0.1`. De toute manière on doit utiliser le même pour le front et le back pour que les cookies fonctionnent, non ?

2023-02-28 07:26 UTC, TimothyPeck commented
j'ai juste copié du workshop

2023-02-28 14:25 UTC, Xstoudi approved these changes

2023-02-28 14:43 UTC, Xstoudi requested changes

2023-02-28 14:43 UTC, Xstoudi commented on api/firstpassapp/views.py
> +    if password != password_verify:
Je ferais pas de message différents pour la vérif du mot de passe et du nom d'utilisateur histoire de pas leak l'existence d'un compte utilisateur.

2023-02-28 14:43 UTC, Xstoudi commented on frontend/src/helpers/fetch-wrapper.js
>    return isLogged && isApiUrl ? { Authorization: `Bearer ${user.token}` } : {};
Evite l'utilisation du Bearer token : on veut s'auth avec les cookies (check le message de Jeanne sur Teams)

2023-03-05 09:52 UTC, Xstoudi approved these changes

2023-03-05 10:07 UTC, merged